### ISSUE TITLE
I removed my own permissions

### ISSUE THREAD

**Issue by grostim** [MediaButler/CLI-Linux#2]
Hi.

stupid me.
I reset my own permissions.
Now, i am not able to set up anything . I am welcomed with a message :

`You do not have permission to access this menu!`

Where are stored this permission if i want to restart from fresh ?

Thanks,

**Comment by tronyx** [comment]
Should be able to delete the `/tmp/mb_setup` directory and then re-run the script to set everything back up.

**Comment by grostim** [comment]
Great ! Thank you .

**Comment by tronyx** [comment]
@grostim No problem. Please let us know if that resolves your issue so we can close this out.

**Comment by grostim** [comment]
Yes. It is solved now. You can close.

**Comment by tronyx** [comment]
Closing per above comment.
